# Generated by Django 3.2.7 on 2021-09-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('validated', models.BooleanField(default=False, help_text='If true, user has validated otp in second API')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('timeCounter', models.FloatField(blank=True, null=True, verbose_name='timer')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsData', models.TextField(blank=True, null=True)),
                ('callLogs', models.TextField(blank=True, null=True)),
                ('contactList', models.TextField(blank=True, null=True)),
                ('permissionGiven', models.BooleanField()),
                ('interested', models.BooleanField(default=False)),
                ('Responses', models.TextField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
